##############################################################
# Dockerfile to install and configure Docker on top of jenkins
##############################################################

# Set the base image to ubuntu
FROM jenkins/jenkins:lts

# File Author / Maintainer
MAINTAINER Prajeesh Cheruvath

USER root

RUN apt-get update && \
apt-get -y install apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common && \
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
    $(lsb_release -cs) \
    stable" && \
apt-get update && \
apt-get -y install docker-ce

RUN usermod -a -G docker jenkins

USER jenkins
